### ISSUE TITLE
Unexpected Result

### ISSUE THREAD

**Issue by HLHsieh** [holstegelab/treat#4]
Hi there,

Thank you for developing this fantastic method. I ran the following command and got the corresponding results:

```
TREAT.py reads -i TR.10x.sorted.bam -b LongTR.bed -o test_output_3 -r /genome/genome.fa -w 10 -t 2 -p None -m None -d 0.1 -minSup 1 -minCov 1

#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	TR.10x.sorted
chr9	27573529	chr9:27573529-27573546	18.0	.	.	PASS	nan;nan	QC;GT;MOTIF;CN;CN_REF;DP	PASS_ASM;17.0|96.0;NA|CCCCGG;NA|15.3;nan|nan;8|1
```

I have confirmed that this region has approximately 10x coverage, and I am wondering whether this result is due to lower coverage. How can I avoid this issue? Additionally, why does it show the information for REF and ALT in the result?

Could you also provide more information on how to interpret the results? Specifically, I would like to understand the differences between GT, MOTIF, and CN.

Thank you for your time and assistance!

Best,
Hsin

**Comment by TesiNicco** [comment]
Hi Hsin,

When using the _reads_ mode, the output VCF will not report allele sequences, but rather allele sizes. This is because alleles are identified using a clustering framework based on allele sizes.

- REF [18] indicates the size of the region of interest in the reference genome
- ALT [.] is always empty for the _reads_ mode
- INFO [nan;nan] allele-specific motif annotation in the reference genome
- GT [17|96] allele-specific sizes. One allele has size 17, the other has size 96
- MOTIF [NA|CCCCGG] allele-specific motif annotation. The first allele (size 17) has no annotation, while the second allele (size 96) contains a CCCCGG motif.
- CN [NA|15.3] allele-specific number of copies of the motif. The first allele has no copies (no annotation in MOTIF), while the second has 15 copies. So the second allele (size 96) is composed of 15 copies of CCCCGG motif.
- CN_REF [nan|nan] this would normally force the sample-motif to be the same as the reference motif, and would report approximate number of copies. In this case is NA as no motif was found in the reference.
- DP [8|1] allele-specific coverage. The first allele (size 17) was represented by 8 reads, while the second (size 96) by only 1 read.

Altogether, your results show that in your sample one allele has the same size as the reference, with no annotation in terms of repeat content. The other allele has lower coverage (only 1 read), it is a larger allele (size 96) and it is composed of 15 copies of CCCCGG motif. The question is how much you can trust this call as it comes from only 1 read.

I'm not completely sure what was unexpected in the results. If you can clarify, i can help you further.

You may want to consider running _otter_ to get the assembled allele sequences: _otter_ will adapt the minimum number of supporting reads per allele based on the total coverage. 

Hope this clarifies
Best,
Nicco

**Comment by HLHsieh** [comment]
Hi Nicco,

Thank you for your quick response and valuable suggestions. I consider the results unexpected, as this is simulated data with only one allele containing 10 copies of GGCCCC or CCCCGG.

I have a few follow-up questions:
1. Why does the first allele (size 17) lack annotation? How does TREAT obtain the annotation information?
2. TREAT contains several modules: reads, assembly, analysis, and plot. Could I consider the reads and assembly modules for genotyping purposes, and use the analysis and plot modules for the other two features? Furthermore, the main difference between reads and assembly is that reads performs reads spanning and motif analysis, while assembly involves an additional assembly step. Is that correct?
3. I tried the assembly module, and it returned better and more expected results. I also tested executing otter directly (rather than through the assembly module in TREAT) to get the assembly results, but found that the result from the assembly module was closer to the expected outcome. I’m curious to know how TREAT achieves better results.
I executed the following commands for analysis:
```
TREAT.py assembly -i C9ORF72_4_10R_NanoSim_30x.sorted.bam -b LongTR.bed -o treat -r genome.fa

otter assemble -b LongTR.bed -r /genome.fa -R D4Z4 --fasta C9ORF72_4_10R_NanoSim_30x.sorted.bam > assembly.fa
```
And the corresponding results were:
```
>C9ORF72_4_10R_NanoSim_30x.sorted.fa#chr9:27573529-27573546#0#tc:i:64#ac:i:34#sc:i:34
CCCGGCCCCGGCCCCGGCCCCGGCCCCGGCCCCGGCCCCTAGCGCGCGACTCCTGAGTT

>C9ORF72#chr9:27573529-27573546#0#tc:i:2#ac:i:1#sc:i:1
GGCCCCGGCCCCGGCCCC
```
4. Is there a length limitation when using TREAT, such as for motif size or the entire TR size? I would like to apply TREAT to larger TR regions.
5.  I am trying more analysis using TREAT.py assembly, but I am encountering some errors and confusion. Could you provide some guidance or troubleshooting tips?

5-1 I executed the command `TREAT.py assembly -i XXX.sorted.bam -b XXX.bed -o treat -r genome.fa`, and extracted the following results. For example, I see results like CGCC;5;193. Is the “CGCC” the motif, and “5” and “193” refer to the motif’s size for each allele? The “+” symbol seems to connect the motif with its corresponding size. Is it possible to consider all motifs as a TR and get their total size?
```
chr11	639992	chr11:639992-640184	CACCCGCGCCCCGCCTCCCCCAGGACCCCTGCGGCCCCGACT....GCTCC	TCCCCCACGCCCGCCGCGCCCGGCCTCCCCCAGGACCCCTGCGGCCCCGACTGTGCGCCCCCCGCGCCCCGCCTCCCCCAGGACCTCTGCGTCCCTGACTGTGCGCCCCCCGCGCCCGGCCTCCCCCGGGGTCCCTGTGGCCCCGACTGTGCGTCCCCCGCGCCCGGCCTCCCCCGGGGTCCCTGTGGCCCCGACTGTGCGTCCCCCGCGCCCC...GCGCCCCCCGACGCC	.	.	
CGCC;5;193	
QC;GT;GT_LEN;MOTIF;CN;CN_REF;DP	
PASS;1|1;10965|10965;ACAGTCGGGGCCGCAGGGGTCCGGGGGGAGGCCGGGCGCGGGGGGCGC+AACTGTGCTCCCGCCGCGCCCGGCCTCCCCCCGGACCCCTGCGGCTCC+ACAGTCGGGGCCGCAGGGGTCCGGGGGGAGGCCGGGCGCGGGGGGCGC+ACAGTCGGGGCCGCAGGGGTCCTGGGGGAGGCTGGGCGCGGCGGGCGC+AACTGTGCTCCCGCCGCGCCCGGCCTCCCCCCGGACCCCTGCGGCTCC+ACAGTCGGGGCCGCAGGGGTCCTGGGGGAGGCCGGGCGCGGGGGGCGC+ACAGGGACCCCGGGGGAGGCCGGGCGCGGGGGACGCACAGTCGGGGCC+ACAGTCGGGGCCGCAGGGGTCCTGGGGGAGGCGGGGCGCGGGTGGCGC+ACAGGGACCCCGGGGGAGGCCGGGCGCGGGGGACGCACAGTCGGGGCC|ACAGTCGGGGCCGCAGGGGTCCGGGGGGAGGCCGGGCGCGGGGGGCGC+AACTGTGCTCCCGCCGCGCCCGGCCTCCCCCCGGACCCCTGCGGCTCC+ACAGTCGGGGCCGCAGGGGTCCGGGGGGAGGCCGGGCGCGGGGGGCGC+ACAGTCGGGGCCGCAGGGGTCCTGGGGGAGGCTGGGCGCGGCGGGCGC+AACTGTGCTCCCGCCGCGCCCGGCCTCCCCCCGGACCCCTGCGGCTCC+ACAGTCGGGGCCGCAGGGGTCCTGGGGGAGGCCGGGCGCGGGGGGCGC+ACAGGGACCCCGGGGGAGGCCGGGCGCGGGGGACGCACAGTCGGGGCC+ACAGTCGGGGCCGCAGGGGTCCTGGGGGAGGCGGGGCGCGGGTGGCGC+ACAGGGACCCCGGGGGAGGCCGGGCGCGGGGGACGCACAGTCGGGGCC;4+3.9583333333333335+3.9791666666666665+3.9791666666666665+3.9583333333333335+3.9791666666666665+3.9583333333333335+4.0+3.9583333333333335|4+3.9583333333333335+3.9791666666666665+3.9791666666666665+3.9583333333333335+3.9791666666666665+3.9583333333333335+4.0+3.9583333333333335;2741.25|2741.25;49|49
```

5-2 Error: `TREAT.py assembly -b XXX.bed -o treat -r genome.fa -i XXX.sorted.bam`
```
** Assembler: otter
(Fri Dec 20 21:26:12 2024): Loaded 1 total annotation(s)
(Fri Dec 20 21:26:12 2024): Processing DRD4_4_10R_NanoSim_30x.sorted.bam (DRD4_4_10R_NanoSim_30x.sorted.fa)
(Fri Dec 20 21:26:12 2024): [WARNING] No spanning reads for chr9:27573528-27573546
*** Otter took 0.0 seconds
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/hsinlun/miniconda3/envs/treat/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/hsinlun/miniconda3/envs/treat/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/hsinlun/bin/TREAT/bin/functions_assembly_based.py", line 179, in run_trf_asm_opt
    fa = pyfastx.Fastx(x, uppercase=True)
RuntimeError: treat/otter_local_asm/DRD4_4_10R_NanoSim_30x.sorted.fa is not fasta or fastq sequence file
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/hsinlun/bin/TREAT/bin/assembly_based.py", line 27, in <module>
    df_trf_phasing_combined = otterPipeline_opt(outDir, cpu, ref, bed_dir, inBam, count_reg, windowAss, window, bed, omitNonSpanning, otterMaxCov, otterCovFrac, otterMinSim, ploidy)
  File "/hsinlun/bin/TREAT/bin/functions_assembly_based.py", line 242, in otterPipeline_opt
    trf_asm_res = pool.map(trf_asm, extract_results)
  File "/hsinlun/miniconda3/envs/treat/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/hsinlun/miniconda3/envs/treat/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
RuntimeError: treat/otter_local_asm/DRD4_4_10R_NanoSim_30x.sorted.fa is not fasta or fastq sequence file
```
I tried `TREAT.py reads -b NanoRepeat_chr11_v2.bed -o treat -r genome.fa -i DRD4_10_10R_NanoSim_30x.sorted.bam`
```
** Producing outputs: VCF file and table with sequences
Haplotyping analysis done!
Traceback (most recent call last):
  File "/hsinlun/bin/TREAT/bin/read_based.py", line 105, in <module>
    df_seq, df_raw = haplotyping_steps(data = df_trf_phasing_combined, n_cpu = cpu, thr_mad = HaploDev, min_support = minimumSupport, type = 'reads', outDir = outDir, all_clipping_df = all_clipping_df, inBam = inBam)
  File "/hsinlun/bin/TREAT/bin/functions_read_based.py", line 660, in haplotyping_steps
    return df_seq, raw_seq_df
UnboundLocalError: local variable 'raw_seq_df' referenced before assignment

```
I truly believe there are reads spanning this region (as checked by IGV), but why were no reads detected in the output? How can I fix this issue?

5-3 Error: `TREAT.py reads -b XXX.bed -o treat -r genome.fa -i XXX.sorted.bam`
```
* Loading libraries
* Analysis started
** Output directory valid.
** Log file written to treat/treat_run.log
** BED file: found 1 regions in 1 chromosomes
** All intervals are valid.
** BAM file(s): found single bam
** Exact SV intervals extracted
** Exact SV intervals from reference extracted
** Read extraction took 1.0 seconds
Error: Could not load sequence. Empty file or bad format.
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/hsinlun/miniconda3/envs/treat/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/hsinlun/miniconda3/envs/treat/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/hsinlun/bin/TREAT/bin/functions_read_based.py", line 417, in run_trf
    tmp_trf_match = [read_id + '_' + region.replace('@', ''), 'NA'] + trf[x].split()
UnboundLocalError: local variable 'read_id' referenced before assignment
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/hsinlun/bin/TREAT/bin/read_based.py", line 62, in <module>
    trf_results = pool.map(trf_fun, index_fasta)
  File "/hsinlun/miniconda3/envs/treat/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/hsinlun/miniconda3/envs/treat/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
UnboundLocalError: local variable 'read_id' referenced before assignment
```

Looking forward to your insights.

Best regards,
Hsin

**Comment by TesiNicco** [comment]
Hi Hsin,

sorry for the very late reply. Let me try to answer your questions:

1. [Why does the first allele (size 17) lack annotation? How does TREAT obtain the annotation information?]
TREAT performs motif annotation using `pytrf` library (an adaptation of trf). In some cases, `pytrf` does not annotate the sequence if there is no significant evidence for a repetitive pattern.

2. [TREAT contains several modules: reads, assembly, analysis, and plot. Could I consider the reads and assembly modules for genotyping purposes, and use the analysis and plot modules for the other two features? Furthermore, the main difference between reads and assembly is that reads performs reads spanning and motif analysis, while assembly involves an additional assembly step. Is that correct?]
That's correct. _Reads_ and _Assembly_ are the genotyping engines: _Reads_ uses all reads spanning the (repetitive) region(s) of interest, while _Assembly_ creates a consensus sequence (of the region of interest) from the reads spanning the region(s) of interest. For this reason, we suggest to use the _Assembly_ module as main genotyping engine. As you also say, Analysis and Plot are for analysis and visualisation purposes only.

3. I tried the assembly module, and it returned better and more expected results. I also tested executing otter directly (rather than through the assembly module in TREAT) to get the assembly results, but found that the result from the assembly module was closer to the expected outcome. I’m curious to know how TREAT achieves better results.]
Probably this is due to the parameters applied to otter. By default, TREAT uses this command:
`otter assemble -a 2 -c 200 --fasta -b regions.bed -r reference.fa -R sample_name sample.bam -t threads -o 10 -A 500,0.1 -s 0.9 > output_consensus.fa`

4. [Is there a length limitation when using TREAT, such as for motif size or the entire TR size? I would like to apply TREAT to larger TR regions.]
There's no limitation to the total TR size TREAT can identify, as long as there are reads spanning the region. So the limitation is mostly on the read length. As for the motif identification, it struggles with very large motifs, but you should still get some output. If you need to precisely annotate repeat content, take a look at our other tool [MotifScope](https://github.com/holstegelab/MotifScope). We also plan to include it in a newer version of TREAT.

5-1. [ I executed the command TREAT.py assembly -i XXX.sorted.bam -b XXX.bed -o treat -r genome.fa, and extracted the following results. For example, I see results like CGCC;5;193. Is the “CGCC” the motif, and “5” and “193” refer to the motif’s size for each allele? The “+” symbol seems to connect the motif with its corresponding size. Is it possible to consider all motifs as a TR and get their total size?]
From what i can see, the CGCC;5;193 is about the motif annotation and length in the reference genome. 5 copies of CGCC and a total size of 193 bp. As you can see from the reference allele sequence, it is very variable the motif here, so TREAT struggles with the annotation. You may want to try MotifScope in this case. The “+” symbol connects different motif annotations. The total size is always given in the output in the _GT_LEN_ field (in your case, 10965|10965).

Regarding the other errors, did you check the input is a genuine bam file? This is an interesting case, if you want you can share a couple reads from the bam file and i can further help you.

Sorry again for the late message, hope it still helps
Nicco

**Comment by HLHsieh** [comment]
Hi Nicco,

I appreciate your kind response to my questions. I am still interested in gaining a deeper understanding.

Following up on Q4 and 5.1, thank you for suggesting MotifScope; I will explore it, and I look forward to the new version of TREAT.

I noticed that TREAT tends to break large motifs into smaller ones for structural variation identification. Therefore, I am wondering whether it would be reasonable to estimate the copy number of a 48-bp tandem repeat by dividing the GT_LEN by the motif length (e.g., 10965 / 48). Do you think this would be an appropriate way to infer the copy number of this TR using TREAT?

I also attempted to sum the copy numbers provided for each motif (4 + 3.9583333333333335 + 3.9791666666666665 + 3.9791666666666665 + 3.9583333333333335 + 3.9791666666666665 + 3.9583333333333335 + 4.0 + 3.9583333333333335), but the result did not match my expectation.

Example:
```
chr11	639992	chr11:639992-640184	CACCCGCGCCCCGCCTCCCCCAGGACCCCTGCGGCCCCGACT....GCTCC	TCCCCCACGCCCGCCGCGCCCGGCCTCCCCCAGGACCCCTGCGGCCCCGACTGTGCGCCCCCCGCGCCCCGCCTCCCCCAGGACCTCTGCGTCCCTGACTGTGCGCCCCCCGCGCCCGGCCTCCCCCGGGGTCCCTGTGGCCCCGACTGTGCGTCCCCCGCGCCCGGCCTCCCCCGGGGTCCCTGTGGCCCCGACTGTGCGTCCCCCGCGCCCC...GCGCCCCCCGACGCC	.	.	
CGCC;5;193	
QC;GT;GT_LEN;MOTIF;CN;CN_REF;DP	
PASS;1|1;10965|10965;ACAGTCGGGGCCGCAGGGGTCCGGGGGGAGGCCGGGCGCGGGGGGCGC+AACTGTGCTCCCGCCGCGCCCGGCCTCCCCCCGGACCCCTGCGGCTCC+ACAGTCGGGGCCGCAGGGGTCCGGGGGGAGGCCGGGCGCGGGGGGCGC+ACAGTCGGGGCCGCAGGGGTCCTGGGGGAGGCTGGGCGCGGCGGGCGC+AACTGTGCTCCCGCCGCGCCCGGCCTCCCCCCGGACCCCTGCGGCTCC+ACAGTCGGGGCCGCAGGGGTCCTGGGGGAGGCCGGGCGCGGGGGGCGC+ACAGGGACCCCGGGGGAGGCCGGGCGCGGGGGACGCACAGTCGGGGCC+ACAGTCGGGGCCGCAGGGGTCCTGGGGGAGGCGGGGCGCGGGTGGCGC+ACAGGGACCCCGGGGGAGGCCGGGCGCGGGGGACGCACAGTCGGGGCC|ACAGTCGGGGCCGCAGGGGTCCGGGGGGAGGCCGGGCGCGGGGGGCGC+AACTGTGCTCCCGCCGCGCCCGGCCTCCCCCCGGACCCCTGCGGCTCC+ACAGTCGGGGCCGCAGGGGTCCGGGGGGAGGCCGGGCGCGGGGGGCGC+ACAGTCGGGGCCGCAGGGGTCCTGGGGGAGGCTGGGCGCGGCGGGCGC+AACTGTGCTCCCGCCGCGCCCGGCCTCCCCCCGGACCCCTGCGGCTCC+ACAGTCGGGGCCGCAGGGGTCCTGGGGGAGGCCGGGCGCGGGGGGCGC+ACAGGGACCCCGGGGGAGGCCGGGCGCGGGGGACGCACAGTCGGGGCC+ACAGTCGGGGCCGCAGGGGTCCTGGGGGAGGCGGGGCGCGGGTGGCGC+ACAGGGACCCCGGGGGAGGCCGGGCGCGGGGGACGCACAGTCGGGGCC;4+3.9583333333333335+3.9791666666666665+3.9791666666666665+3.9583333333333335+3.9791666666666665+3.9583333333333335+4.0+3.9583333333333335|4+3.9583333333333335+3.9791666666666665+3.9791666666666665+3.9583333333333335+3.9791666666666665+3.9583333333333335+4.0+3.9583333333333335;2741.25|2741.25;49|49
```

Other questions:
1.	Parameters
```
-minSup / --minimumSupport: during haplotype calling, the minimum number of reads supporting each haplotyping. Default is 2.
-minCov / --minimumCoverage: during haplotype calling, the minimum number of total reads necessary for calling. Default is 5.
-p / --ploidy: estimated ploidy of the sample. Default value is 2 for autosomal regions. For sex-specific regions, the ploidy is either 1 (for males with chrX and chrY present in the BAM file), or 2 (for females with 2 chrX).
```
I tried to apply `-minSup` and `-minCov` to the `TREAT.py assembly` command, but it did not work. Additionally, regarding --ploidy, can it be used to set a ploidy level greater than 2, or is it intended only for specifying diploid/sex chromosome ploidy adjustments?

2. Is there any way to gain insights into detecting mosaicism with TREAT?

I cannot locate the file that caused the errors, but if I retrieve it, I will share it with you.

Many thanks,
Hsin
